create table if not exists passports
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       CHARACTER VARYING(100)                  NOT NULL,
    surname    CHARACTER VARYING(100)                  NOT NULL,
    patronymic CHARACTER VARYING(100)                  NOT NULL,
    birthday   CHARACTER VARYING(100)                  NOT NULL,
    address    CHARACTER VARYING(200)                  NOT NULL,
    CONSTRAINT passport_pk PRIMARY KEY (id)
);

create table if not exists users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    CHARACTER VARYING(100)                  NOT NULL,
    email       CHARACTER VARYING(100)                  NOT NULL,
    passport_id BIGINT,
    CONSTRAINT user_pk PRIMARY KEY (id),
    CONSTRAINT passport_fk FOREIGN KEY (passport_id) REFERENCES passports (id) ON DELETE CASCADE
);

create table if not exists courses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            CHARACTER VARYING(100)                  NOT NULL,
    price           DOUBLE PRECISION                        NOT NULL CHECK ( price >= 0 ),
    months_duration SMALLINT                                NOT NULL CHECK ( price > 0 ),
    CONSTRAINT course_pk PRIMARY KEY (id)
);



create table if not exists users_courses
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT user_course_pk PRIMARY KEY (user_id, course_id),
    CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT course_fk FOREIGN KEY (course_id) REFERENCES courses (id)
);

